### ISSUE TITLE
Add support for input functions (getters) and input vars

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [sddec-13/casters-and-coders#31]
**Feature**
We need to support the ability for the user to call a getter function and to use variables set by external nodes.

**Comment by brenno263** [comment]
Honestly this could be as simple as:

```python
cache = {}

// in output callback
emit_signal(...)
if def["returns"]:
    return cache[puzzle_name][output_name]

// update cache values
update_value(puzzle_name, output_name, return_value):
    cache[puzzle_name][output_name] = return_value

// when unloading a puzzle
del cache[puzzle_name]

```

This would give us support for getters without args, returning asynchronously updated values. I think for where the project is at right now, this is an effective gradual step.

**Comment by AutonomicPerfectionist** [comment]
Yeah that was pretty much how I did it in the attached branch, but my laptop died before I could make a PR...
